name: mobile_wallet
description: QRL Mobile Wallet

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  protobuf: ^2.1.0
  grpc: ^3.0.2
  ffi: ^2.0.1
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  flutter_secure_storage: ^6.0.0
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  decimal: ^2.3.0
  fixnum: ^1.0.1
  wakelock: ^0.6.2
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.2.1
  http: ^0.13.5
  local_auth: ^2.1.2
  secure_application: ^3.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.2.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/qrl-logo.png
    - assets/images/qrl-tree.png
    - assets/images/orange-dots.png
    - assets/images/background-balance.png
  fonts:
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          style: italic
